### ISSUE TITLE
AttributeError: module 'sparseconvnet.SCN' has no attribute 'Metadata_2'

### ISSUE THREAD

**Issue by shahaamirbader** [dbraun-ub/NQGN#2]
I am trying to train the model myself. I have a conda environment with following packages:

```
(QGN) xubuntu@08d6013cfe2d:/homelocal/NQGN$ conda list
# packages in environment at /home/xubuntu/.conda/envs/QGN:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
attrs                     21.2.0             pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0    anaconda
blas                      1.0                         mkl  
brotlipy                  0.7.0           py36h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.17.1               h27cfd23_0  
ca-certificates           2022.07.19           h06a4308_0    anaconda
certifi                   2021.5.30        py36h06a4308_0    anaconda
cffi                      1.14.6           py36h400218f_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
cloudpickle               2.0.0              pyhd3eb1b0_0    anaconda
cryptography              3.4.7            py36hd23ed53_0  
curl                      7.78.0               h1ccaba5_0  
cycler                    0.11.0             pyhd3eb1b0_0    anaconda
cytoolz                   0.11.0           py36h7b6447c_0    anaconda
daiquiri                  3.0.0              pyhd3deb0d_0    conda-forge
dask-core                 2021.3.1           pyhd3eb1b0_0    anaconda
dataclasses               0.8                      pypi_0    pypi
decorator                 5.1.1              pyhd3eb1b0_0    anaconda
deprecated                1.2.12             pyhd3eb1b0_0  
expat                     2.4.1                h2531618_2  
freetype                  2.11.0               h70c0345_0  
gettext                   0.21.0               hf68c758_0  
git                       2.32.0          pl5262hc120c5b_1  
git-pull-request          6.0.1              pyh9f0ad1d_1    conda-forge
hdf5                      1.10.2               hba1933b_1  
icu                       58.2                 he6710b0_3  
idna                      3.2                pyhd3eb1b0_0  
imageio                   2.9.0              pyhd3eb1b0_0    anaconda
intel-openmp              2021.4.0          h06a4308_3561  
ipython                   7.16.1           py36h5ca1d4c_0    anaconda
ipython_genutils          0.2.0              pyhd3eb1b0_1    anaconda
jedi                      0.18.0           py36h06a4308_1    anaconda
jpeg                      9d                   h7f8727e_0  
kiwisolver                1.3.1            py36h2531618_0    anaconda
krb5                      1.19.2               hac12032_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libcurl                   7.78.0               h0b77cf5_0  
libedit                   3.1.20210910         h7f8727e_0  
libev                     4.33                 h7f8727e_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   9.3.0               h5101ec6_17  
libiconv                  1.15                 h63c8f33_5  
libnghttp2                1.41.0               hf8bcb03_2  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h7b6447c_0  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtiff                   4.2.0                h85742a9_0  
libwebp-base              1.2.0                h27cfd23_0  
libxml2                   2.9.12               h03d6c58_0  
lz4-c                     1.9.3                h295c915_1  
matplotlib-base           3.3.4            py36h62a2d02_0    anaconda
mkl                       2020.2                      256  
mkl-service               2.3.0            py36he8ac12f_0  
mkl_fft                   1.3.0            py36h54f3939_0  
mkl_random                1.1.1            py36h0573a6f_0  
ncurses                   6.3                  heee7806_1  
networkx                  2.5                        py_0    anaconda
numpy                     1.19.2           py36h54aff64_0  
numpy-base                1.19.2           py36hfa32c7d_0  
olefile                   0.46                     py36_0  
opencv                    3.4.1            py36h6fd60c2_1  
opencv-python             4.5.4.58                 pypi_0    pypi
openssl                   1.1.1q               h7f8727e_0    anaconda
parso                     0.8.3              pyhd3eb1b0_0    anaconda
pcre2                     10.35                h14c3975_1  
perl                      5.26.2               h14c3975_0  
pexpect                   4.8.0              pyhd3eb1b0_3    anaconda
pickleshare               0.7.5           pyhd3eb1b0_1003    anaconda
pillow                    8.2.0            py36he98fc37_0  
pip                       21.2.2           py36h06a4308_0  
prompt-toolkit            3.0.20             pyhd3eb1b0_0    anaconda
protobuf                  3.19.4                   pypi_0    pypi
ptyprocess                0.7.0              pyhd3eb1b0_2    anaconda
pycparser                 2.20                       py_2  
pygithub                  1.55               pyhd3eb1b0_1  
pygments                  2.11.2             pyhd3eb1b0_0    anaconda
pyjwt                     2.1.0            py36h06a4308_0  
pynacl                    1.4.0            py36h7b6447c_1  
pyopenssl                 21.0.0             pyhd3eb1b0_1  
pyparsing                 3.0.4              pyhd3eb1b0_0    anaconda
pysocks                   1.7.1            py36h06a4308_0  
python                    3.6.13               h12debd9_1  
python-dateutil           2.8.2              pyhd3eb1b0_0    anaconda
python-json-logger        2.0.1                      py_0  
pywavelets                1.1.1            py36h7b6447c_2    anaconda
pyyaml                    5.4.1            py36h27cfd23_1    anaconda
readline                  8.1                  h27cfd23_0  
requests                  2.26.0             pyhd3eb1b0_0  
scikit-image              0.17.2           py36hdf5156a_0    anaconda
scipy                     1.2.1            py36h7c811a0_0  
setuptools                58.0.4           py36h06a4308_0  
six                       1.16.0             pyhd3eb1b0_0  
sparseconvnet             0.2                      pypi_0    pypi
sqlite                    3.36.0               hc218d9a_0  
tensorboardx              2.5.1                    pypi_0    pypi
tifffile                  2020.10.1        py36hdd07704_2    anaconda
tk                        8.6.11               h1ccaba5_0  
toolz                     0.11.2             pyhd3eb1b0_0    anaconda
torch                     1.10.0+cu113             pypi_0    pypi
torchaudio                0.10.0+cu113             pypi_0    pypi
torchvision               0.11.1+cu113             pypi_0    pypi
tornado                   6.1              py36h27cfd23_0    anaconda
traitlets                 4.3.3            py36h06a4308_0    anaconda
typing-extensions         3.10.0.2                 pypi_0    pypi
unrar                     0.4                      pypi_0    pypi
urllib3                   1.26.7             pyhd3eb1b0_0  
wcwidth                   0.2.5              pyhd3eb1b0_0    anaconda
wheel                     0.37.0             pyhd3eb1b0_1  
wrapt                     1.12.1           py36h7b6447c_1  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0    anaconda
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                haebb681_0
```

But when I try to train the model on Kitti dataset, it gives following error. Although I have installed Sparseconvnet but seems like an issue with some dependencies. Could you share what environment and packages are required to run training. May be short readme file would be helpful. Also I would suggest to upload Sparseconvnet folder, as there may be several changes in Sparseconvnet files to match the latest dependencies.  Thanks.

```
QGN) xubuntu@08d6013cfe2d:/homelocal/NQGN$ CUDA_VISIBLE_DEVICES=1,2,3 python train.py --png
Training model named:
   mdp
Models and tensorboard events files are saved to:
   /home/xubuntu/tmp
Training is using:
   cuda
/home/xubuntu/.conda/envs/QGN/lib/python3.6/site-packages/torchvision/transforms/transforms.py:288: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
Using split:
   eigen_zhou
There are 39810 training items and 4424 validation items

range(0, 20)
/home/xubuntu/.conda/envs/QGN/lib/python3.6/site-packages/torch/optim/lr_scheduler.py:134: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Training
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    trainer.train()
  File "/homelocal/NQGN/trainer.py", line 158, in train
    self.run_epoch()
  File "/homelocal/NQGN/trainer.py", line 176, in run_epoch
    outputs, losses = self.process_batch(inputs)
  File "/homelocal/NQGN/trainer.py", line 209, in process_batch
    quad, mask = self.models["depth"](features, None, crit=self.opt.crit)
  File "/home/xubuntu/.conda/envs/QGN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/homelocal/NQGN/networks/depth_decoder.py", line 180, in forward
    in4 = self.dense_to_sparse(in4)
  File "/home/xubuntu/.conda/envs/QGN/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/homelocal/QGN/SparseConvNet/sparseconvnet/denseToSparse.py", line 27, in forward
    output.metadata = Metadata(self.dimension)
  File "/homelocal/QGN/SparseConvNet/sparseconvnet/metadata.py", line 17, in Metadata
    return getattr(sparseconvnet.SCN, 'Metadata_%d'%dim)()
AttributeError: module 'sparseconvnet.SCN' has no attribute 'Metadata_2'

```

**Comment by dbraun-ub** [comment]
There is something wrong with your sparseconvnet library. Make sure to follow the installation process here: https://github.com/facebookresearch/SparseConvNet


Here is my config:
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alsa-lib                  1.2.6.1              h7f98852_0    conda-forge
aom                       3.4.0                h27087fc_1    conda-forge
attr                      2.5.1                h166bdaf_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h166bdaf_7    conda-forge
brotli-bin                1.0.9                h166bdaf_7    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.6.15            ha878542_0    conda-forge
cairo                     1.16.0            ha61ee94_1011    conda-forge
certifi                   2022.6.15        py37h89c1867_0    conda-forge
cudatoolkit               10.1.243            h8cb64d8_10    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
expat                     2.4.8                h27087fc_0    conda-forge
ffmpeg                    4.4.2           gpl_h512afef_105    conda-forge
fftw                      3.3.10          nompi_h77c792f_102    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               h8e229c2_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.34.4           py37h540881e_0    conda-forge
freeglut                  3.2.2                h9c3ff4c_1    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glib                      2.72.1               h6239696_0    conda-forge
glib-tools                2.72.1               h6239696_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gnutls                    3.7.6                hf3e180e_5    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
gst-plugins-base          1.20.3               hf6a322e_0    conda-forge
gstreamer                 1.20.3               hd4edc92_0    conda-forge
harfbuzz                  4.4.1                hf9f4e7c_0    conda-forge
hdf5                      1.12.1          nompi_h2386368_104    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
intel-openmp              2022.0.1          h06a4308_3633  
ipython                   7.33.0           py37h89c1867_0    conda-forge
jack                      1.9.18            h8c3723f_1002    conda-forge
jasper                    2.0.33               ha77e612_0    conda-forge
jedi                      0.18.1           py37h89c1867_1    conda-forge
jpeg                      9e                   h166bdaf_1    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4            py37h7cecad7_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
lame                      3.100             h7f98852_1001    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0           14_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_7    conda-forge
libbrotlidec              1.0.9                h166bdaf_7    conda-forge
libbrotlienc              1.0.9                h166bdaf_7    conda-forge
libcap                    2.64                 ha37c62d_0    conda-forge
libcblas                  3.9.0           14_linux64_openblas    conda-forge
libclang                  14.0.6          default_h2e3cab8_0    conda-forge
libclang13                14.0.6          default_h3a83d3e_0    conda-forge
libcups                   2.3.3                hf5a7f15_1    conda-forge
libcurl                   7.83.1               h7bff187_0    conda-forge
libdb                     6.2.32               h9c3ff4c_0    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libdrm                    2.4.112              h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libflac                   1.3.4                h27087fc_0    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libglib                   2.72.1               h2d90d5f_0    conda-forge
libglu                    9.0.0             he1b5a44_1001    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libidn2                   2.3.3                h166bdaf_0    conda-forge
liblapack                 3.9.0           14_linux64_openblas    conda-forge
liblapacke                3.9.0           14_linux64_openblas    conda-forge
libllvm14                 14.0.6               he0ac6c6_0    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.20          pthreads_h78a6416_0    conda-forge
libopencv                 4.6.0            py37h4a49c2f_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpciaccess              0.16                 h516909a_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     14.4                 hd77ab85_0    conda-forge
libprotobuf               3.20.1               h6239696_0    conda-forge
libsndfile                1.0.31               h9c3ff4c_1    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libtasn1                  4.18.0               h166bdaf_1    conda-forge
libtiff                   4.4.0                h0fcbabc_0    conda-forge
libtool                   2.4.6             h9c3ff4c_1008    conda-forge
libudev1                  249                  h166bdaf_4    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libva                     2.15.0               h166bdaf_0    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libvpx                    1.11.0               h9c3ff4c_3    conda-forge
libwebp                   1.2.2                h3452ae3_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.14               h22db469_3    conda-forge
libzlib                   1.2.12               h166bdaf_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
matplotlib                3.5.2            py37h89c1867_0    conda-forge
matplotlib-base           3.5.2            py37hc347a89_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mkl                       2022.0.1           h06a4308_117  
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.0.29               haf5c9bc_1    conda-forge
mysql-libs                8.0.29               h28c427c_1    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nettle                    3.8                  hc379101_0    conda-forge
ninja                     1.11.0               h924138e_0    conda-forge
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.78                 h2350873_0    conda-forge
numpy                     1.21.6           py37h976b520_0    conda-forge
opencv                    4.6.0            py37h89c1867_0    conda-forge
openh264                  2.2.0                h6239696_1    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1q               h166bdaf_0    conda-forge
p11-kit                   0.24.1               hc5aa10d_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.1.1            py37h44f0d7a_0    conda-forge
pip                       22.1.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
ply                       3.11                       py_1    conda-forge
portaudio                 19.6.0               h57a0ea0_5    conda-forge
prompt-toolkit            3.0.29             pyha770c72_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pulseaudio                14.0                 h7f54b18_8    conda-forge
py-opencv                 4.6.0            py37h25bab4e_0    conda-forge
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7           py37hf30b843_0    conda-forge
pyqt5-sip                 12.11.0          py37hd23a5d3_0    conda-forge
python                    3.7.12          hb7a2778_100_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
qt-main                   5.15.4               ha5833f6_2    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
setuptools                61.2.0           py37h06a4308_0  
sip                       6.6.2            py37hd23a5d3_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sparseconvnet             0.2                       dev_0    <develop>
sqlite                    3.38.5               h4ff8645_0    conda-forge
svt-av1                   1.1.0                h27087fc_1    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
torchvision               0.5.0                py37_cu101    pytorch
tornado                   6.2              py37h540881e_0    conda-forge
traitlets                 5.2.2.post1        pyhd8ed1ab_0    conda-forge
typing-extensions         4.3.0                hd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
unicodedata2              14.0.0           py37h540881e_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
x264                      1!161.3030           h7f98852_1    conda-forge
x265                      3.5                  h924138e_3    conda-forge
xcb-util                  0.4.0                h166bdaf_0    conda-forge
xcb-util-image            0.4.0                h166bdaf_0    conda-forge
xcb-util-keysyms          0.4.0                h166bdaf_0    conda-forge
xcb-util-renderutil       0.3.9                h166bdaf_0    conda-forge
xcb-util-wm               0.4.1                h166bdaf_0    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxi                1.7.10               h7f98852_0    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.12               h166bdaf_0    conda-forge
zstd                      1.5.2                h8a70e8d_1    conda-forge
```

Basically, it's working with python 3.7, pytorch 1.4.0 and cudatoolkit 10.1.

**Comment by shahaamirbader** [comment]
Thanks
