### ISSUE TITLE
KeyError: ('cam_T_cam', 0, -1)

### ISSUE THREAD

**Issue by shahaamirbader** [dbraun-ub/NQGN#4]
So I have tried almost everything I could to get rid of this error but it stay. Any help as to how to address this error?

```
(QGNResnet18) [ashah29@compute-0-3 NQGN]$ python train.py --png
Training model named:
   mdp
Models and tensorboard events files are saved to:
   /home/ashah29/tmp
Training is using:
   cuda
Using split:
   eigen_zhou
There are 39810 training items and 4424 validation items

/project/xfu/aamir/anaconda3/envs/QGNResnet18/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:122: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Training
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    trainer.train()
  File "/project/xfu/aamir/NQGN/trainer.py", line 156, in train
    self.run_epoch()
  File "/project/xfu/aamir/NQGN/trainer.py", line 173, in run_epoch
    outputs, losses = self.process_batch(inputs)
  File "/project/xfu/aamir/NQGN/trainer.py", line 222, in process_batch
    self.generate_images_pred(inputs, outputs)
  File "/project/xfu/aamir/NQGN/trainer.py", line 371, in generate_images_pred
    T = outputs[("cam_T_cam", 0, frame_id)]
KeyError: ('cam_T_cam', 0, -1)
```

**Comment by dbraun-ub** [comment]
try with `python train.py --png --frame_ids 0`
The default value is currently '0 -1 1' and requires to couple the depth prediction with a poseNet. It is not implemented here. I'm doing stereo training only.

If you want to do the training with adjacent frames, have a look at the monodepth2 implementation https://github.com/nianticlabs/monodepth2

**Comment by dbraun-ub** [comment]
In the experiments folder, you'll find my default setting for training: 

```
python ../train.py --model_name train_model \
  --data_path=/path/to/kitti \
  --log_dir /path/to/model/save \
  --crit 0.025  \
  --use_stereo --frame_ids 0 --batch_size 6 \
  --load_weights_folder  /path/to/pretrained/model \
  --models_to_load encoder depth \
  --scales 0 1 2 3 4 5
```

**Comment by shahaamirbader** [comment]
Thanks, this helps
